('author','book_number');
INSERT INTO author (author_name, book_number) VALUES ('Rogalla, C. L.','B008TT5Q1M');
INSERT INTO author (author_name, book_number) VALUES ('Witt, Greg','B00GW5KUSE');
INSERT INTO author (author_name, book_number) VALUES ('Golieb, Steven','B00HT67C7W');
INSERT INTO author (author_name, book_number) VALUES ('Day, David','B0719VGR8L');
INSERT INTO author (author_name, book_number) VALUES ('Molvar, Erik','B00263ZL8U');
INSERT INTO author (author_name, book_number) VALUES ('Stutzman, Paul','B0073UNAN4');
INSERT INTO author (author_name, book_number) VALUES ('Copeland, Kathy','B00C0JIWGI');
INSERT INTO author (author_name, book_number) VALUES ('Picard, Tiffany','B00DST990C');
INSERT INTO author (author_name, book_number) VALUES ('Stinchfield, Rick','B00ET9AFFS');
INSERT INTO author (author_name, book_number) VALUES ('Zimms, Xavier','B00KAEU3NU');
INSERT INTO author (author_name, book_number) VALUES ('Schneider, Bill','B00MJD6NL6');
INSERT INTO author (author_name, book_number) VALUES ('Ferguson, Tony','B019M4K7GQ');
INSERT INTO author (author_name, book_number) VALUES ('Schmidt, Laurie','B019AM34RO');
INSERT INTO author (author_name, book_number) VALUES ('Witt, Greg','B00A4JMR3U');
INSERT INTO author (author_name, book_number) VALUES ('Peterson, Eric','B004DCBC0S');
INSERT INTO author (author_name, book_number) VALUES ('Lonely Planet','B00AR85SE8');
INSERT INTO author (author_name, book_number) VALUES ('Jewell, Judy','B00850ZMSM');
INSERT INTO author (author_name, book_number) VALUES ('Chapple, Janet','B00DFM7YDQ');
INSERT INTO author (author_name, book_number) VALUES ('Schneider, Bill','B00MJD6NL6');
INSERT INTO author (author_name, book_number) VALUES ('Schneider, Bill','B00MJD9VQ0');
INSERT INTO author (author_name, book_number) VALUES ('Leftridge, Alan','B00R3MH7U4');
INSERT INTO author (author_name, book_number) VALUES ('Somers, Steven','B004DI7MQK');
INSERT INTO author (author_name, book_number) VALUES ('Sidgwick, Alfred','B0083ZT4JM');
INSERT INTO author (author_name, book_number) VALUES ('Gerard, James W. (James Watson)','B0084ANFD2');
INSERT INTO author (author_name, book_number) VALUES ('Scott, Liz Hamill','B0050C1JRG');
INSERT INTO author (author_name, book_number) VALUES ('Harvard Student Agencies, Inc.','B004NSVH7A');
INSERT INTO author (author_name, book_number) VALUES ('Lonely Planet','B005DXOMHQ');
INSERT INTO author (author_name, book_number) VALUES ('Molvar, Erik','B001TGXNB2');
INSERT INTO author (author_name, book_number) VALUES ('Lane, Brian','B009THHAIA');
INSERT INTO author (author_name, book_number) VALUES ('Talmage, James E.','B001R4COFM');
INSERT INTO author (author_name, book_number) VALUES ('Uchtdorf, Dieter F.','B003DRO5J4');
INSERT INTO author (author_name, book_number) VALUES ('Uchtdorf, Dieter F.','B00823TVQQ');
INSERT INTO author (author_name, book_number) VALUES ('Uchtdorf, Dieter F.','B00867483E');
INSERT INTO author (author_name, book_number) VALUES ('Gibbons, Francis M.','B07914YWRK');
INSERT INTO author (author_name, book_number) VALUES ('Larsen, David','B0016OX376');
INSERT INTO author (author_name, book_number) VALUES ('Ridges, David J.','B008I42P1C');
INSERT INTO author (author_name, book_number) VALUES ('The Church of Jesus Christ of Latter-day Saints','B00BMWEEJ8');
INSERT INTO author (author_name, book_number) VALUES ('The Church of Jesus Christ of Latter-day Saints','B00BMWE99S');
INSERT INTO author (author_name, book_number) VALUES ('Hummel, Sharman Bookwalter','B00GFVT89C');
INSERT INTO author (author_name, book_number) VALUES ('Packer, Layne','B00H8XGR5Y');
INSERT INTO author (author_name, book_number) VALUES ('Ridges, David J.','B008I48ZCU');
INSERT INTO author (author_name, book_number) VALUES ('Ridges, David J.','B008I4IX0Y');
INSERT INTO author (author_name, book_number) VALUES ('Grant Hardy','B07JMWD5VV');
INSERT INTO author (author_name, book_number) VALUES ('Rosenberg, Judy','B0061S3X22');
INSERT INTO author (author_name, book_number) VALUES ('Rosenberg, Judy','B00796LH8C');
INSERT INTO author (author_name, book_number) VALUES ('Deschain, Dean','B00XI87YLE');
INSERT INTO author (author_name, book_number) VALUES ('Stones, Michael','B00RXSTOS6');
INSERT INTO author (author_name, book_number) VALUES ('Glidewell, Barbara','B00QIZUTIO');
INSERT INTO author (author_name, book_number) VALUES ('Selby, Christopher','B00TVJNZQM');
INSERT INTO author (author_name, book_number) VALUES ('Pylarinos, Lindsey','B00KX8PB0I');
INSERT INTO author (author_name, book_number) VALUES ('Bartholomew, Mel','B00BL62GBS');
INSERT INTO author (author_name, book_number) VALUES ('Riotte, Louise','B004A7YINO');
INSERT INTO author (author_name, book_number) VALUES ('Ellis, Barbara W.','B005HITRTK');
INSERT INTO author (author_name, book_number) VALUES ('Turner, Julie','B0085WQ4NW');
INSERT INTO author (author_name, book_number) VALUES ('Reinhart, Peter','B0045OUJ58');
INSERT INTO author (author_name, book_number) VALUES ('Reinhart, Peter','B004IK8PFU');
INSERT INTO author (author_name, book_number) VALUES ('Reinhart, Peter','B019B6XJQK');
INSERT INTO author (author_name, book_number) VALUES ('Sahir, Chef Raj','B00NU453BY');
INSERT INTO author (author_name, book_number) VALUES ('Druker, Marjorie','B007FZSU28');
INSERT INTO author (author_name, book_number) VALUES ('Delpha, John','B00MLM9L3C');
INSERT INTO author (author_name, book_number) VALUES ('Reinhart, Peter','B00JYWW486');
INSERT INTO author (author_name, book_number) VALUES ('Katz, Sandor Ellix','B005GPM8M2');
INSERT INTO author (author_name, book_number) VALUES ('Hertzberg MD, Jeff','B00F1R9D9Q');
INSERT INTO author (author_name, book_number) VALUES ('Hughes, Amanda C.','B01G5MOT8K');
INSERT INTO author (author_name, book_number) VALUES ('Jane, Elizabeth','B01EI2IMQO');
INSERT INTO author (author_name, book_number) VALUES ('Chandler, Jennifer','B002JF1MAG');
INSERT INTO author (author_name, book_number) VALUES ('Ziedrich, Linda','B002IUZLXQ');
INSERT INTO author (author_name, book_number) VALUES ('Wells, Patricia','B004JN1D5U');
INSERT INTO author (author_name, book_number) VALUES ('Goodman, Myra','B0065N0J0W');
INSERT INTO author (author_name, book_number) VALUES ('Sheraton, Mimi','B000SEJCVG');
INSERT INTO author (author_name, book_number) VALUES ('Das, Kaushal','B008WS7GHM');
INSERT INTO author (author_name, book_number) VALUES ('Tabakova, Vesela','B00DFZ47G0');
INSERT INTO author (author_name, book_number) VALUES ('Northrup, Tony','B006KY2VZ2');
INSERT INTO author (author_name, book_number) VALUES ('Busch, David D.','B0154FFVFE');
INSERT INTO author (author_name, book_number) VALUES ('Mercola, Dr Joseph','B00N6PD2ME');
INSERT INTO author (author_name, book_number) VALUES ('Mercola, Joseph','B06W2KVK1P');
INSERT INTO author (author_name, book_number) VALUES ('Perlmutter, David','B004KPLRJO');
INSERT INTO author (author_name, book_number) VALUES ('Perlmutter, David','B00BAXFCPO');
INSERT INTO author (author_name, book_number) VALUES ('Hatch, John','B0711D8LWT');
INSERT INTO author (author_name, book_number) VALUES ('Nixon, Robin','B07CZ4W8X2');
INSERT INTO author (author_name, book_number) VALUES ('Emrich, Marco','B07DNCPJ84');
INSERT INTO author (author_name, book_number) VALUES ('Myers, Mark','B00H1W9I6C');
INSERT INTO author (author_name, book_number) VALUES ('Lip Phang, Chong','B074MWGNZ3');
INSERT INTO author (author_name, book_number) VALUES ('Swick, Ed','B00121SIGE');
INSERT INTO author (author_name, book_number) VALUES ('Swick, Ed','B005OIQFN4');
INSERT INTO author (author_name, book_number) VALUES ('Swick, Ed','B004H4XKZW');
INSERT INTO author (author_name, book_number) VALUES ('Moser, Joseph W.','B00CWR4X0W');
INSERT INTO author (author_name, book_number) VALUES ('Beidler, James','B01E0K9YBG');
INSERT INTO author (author_name, book_number) VALUES ('Hansen, Kevan M.','B00COW2PKA');
INSERT INTO author (author_name, book_number) VALUES ('Smith, Drew','B01GP0D3AW');
INSERT INTO author (author_name, book_number) VALUES ('MacEntee, Thomas','B00Q732TD0');
INSERT INTO author (author_name, book_number) VALUES ('Morgan, George G.','B00RM4WTEM');
INSERT INTO author (author_name, book_number) VALUES ('Bettinger, Blaine T.','B01N43048J');
INSERT INTO author (author_name, book_number) VALUES ('Amstrong, Chris','B00GIAWDQK');
INSERT INTO author (author_name, book_number) VALUES ('Sharpe, Sampson','B00N0EQHDC');
INSERT INTO author (author_name, book_number) VALUES ('Lin, Jennifer','B001OC7B1Y');
INSERT INTO author (author_name, book_number) VALUES ('Pausch, Randy','B00139VU7E');
INSERT INTO author (author_name, book_number) VALUES ('Hamilton, Bethany','B000FC2LUU');
INSERT INTO author (author_name, book_number) VALUES ('Albom, Mitch','B000PLXEU2');
